name: CI/CD Flask to ECS

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials (set these in GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1  # replace with your region

      # 3. Login to ECR
      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_URI=${{ steps.ecr.outputs.registry }}/flask-web-app:latest
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 5. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_URI
          echo "image pushed to docker!"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4  # Specify your desired Terraform version!

      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform plan
          terraform destroy -auto-approve
          #terraform apply -auto-approve
          # Output vars to github env
          #echo "db_endpoint=$(terraform output -raw db_endpoint)" >> $GITHUB_ENV
          #echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
        env:
          TF_VAR_rds_user: ${{ secrets.RDS_USER }}
          TF_VAR_rds_pass: ${{ secrets.RDS_PASS }}
      - name: check end-point
        run: |
          echo ${{ env.db_endpoint }}

      - name: Test app
        run: |
          EC2_IP="${{ env.ec2_public_ip }}"
          echo "EC2 public IP: $EC2_IP"
          for i in {1..20}; do
            if curl -s http://$EC2_IP:5000 >/dev/null; then
              echo "App is up!"
              break
            else
              echo "Waiting for app..."
              sleep 15
            fi
          done

                
      # #deploy to ecs fargate!!!!
      # - name: Deploy to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: flask-web-app-task-def.json
      #     service: flask-web-app-task-service
      #     cluster: sagi-flask-web-app-cluster
      #     wait-for-service-stability: true
      #     overrides: |
      #       {
      #         "containerOverrides": [{
      #           "name": "flask-web-app",
      #           "environment": [
      #             {"name": "DB_HOST", "value": "${{ env.db_endpoint }}"},
      #             {"name": "DB_USER", "value": "${{ secrets.RDS_USER }}"},
      #             {"name": "DB_PASSWORD", "value": "${{ secrets.RDS_PASS }}"},
      #             {"name": "DB_NAME", "value": "flask_db"}
      #           ]
      #         }]
      #       }
